### ISSUE TITLE
Результат вычислений

### ISSUE THREAD

**Issue by Haronych** [GyverLibs/Forecaster#1]
Библиотека выдаёт некое число. На данный момент интерпретация результата, как я понял, чем меньше число тем лучше погода. Алгоритм Замбретти по картинке из дока предполагает 32 состояния погоды для трех трендов. Сейчас непонятно как соотнести выдаваемое число с таблицей результатов. Как вариант возвращать ещё и тренд. Будет почти по классике 1-9 для падающего, 1-10 для стабильного и 1-13 для растущего. В итоге можно будет выводить адекватный прогноз

**Comment by GyverLibs** [comment]
Замбретти - крайне приближенное эмпирическое наблюдение, сделанное миллион лет назад) достаточно иметь шкалу 0-10, чем выше - тем "хуже" погода, вероятность осадков выше. Даже при узкой шкале оно работает очень приблизительно, 32 варианта это просто смех)))

**Comment by Haronych** [comment]
В целом согласен но раз уж библиотека всё равно вычисляет и тренд и берет коэффициент сезона значит классический алгоритм соблюдается. Ну или хотя бы тренд возвращать, это даже более полезно чем прогноз особенно при резких изменениях )

**Comment by GyverLibs** [comment]
добавил вывод тренда
